---
- name: Task create zetachain directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  with_items:
    - "{{ tendermint_docker_config_mount }}"
    - "{{ tendermint_docker_data_mount }}"
    - "{{ tendermint_docker_wasm_mount }}"
    - "{{ tendermint_host_keys_mount }}"

  # Option 1 - Local genesis JSON file (if genesis_file var is passed)
- name: Task Copy zetachain genesis file
  become_user: root
  become: true
  copy:
    src: "{{ genesis_file }}"
    dest: "{{ tendermint_host_config_mount }}/genesis.json"
    owner: "root"
    group: "root"
    mode: "0644"
  register: genesis_file_cfg
  when: genesis_file is defined and genesis_file != ""

# Option 2 - Remote genesis JSON file
- name: Task Download zetachain genesis file
  get_url:
    url: "{{ genesis_url }}"
    dest: "{{ tendermint_host_config_mount }}/genesis.json"
    owner: "root"
    group: "root"
    checksum: "{{ genesis_checksum }}"
    mode: "0655"
  register: genesis_cfg
  tags: [genesis]
  when: genesis_url is defined and genesis_url != "" and not genesis_is_archive_file

# - name: Task Pull Zetachain Docker Image
#   docker_image:
#     name: jer117/zetachain:v11.0.4-1
#     state: present
#     force_source: no
#     ignore_errors: true

- name: Task Render zetachain config
  become_user: root
  become: true
  template:
    src: tendermint/{{ item }}.j2
    dest: "{{ tendermint_host_config_mount }}/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ tendermint_config_files }}"
  register: cfg

- name: Task Detect if config has changed
  set_fact:
    cfg_changed: "{{ cfg.changed | bool or genesis_cfg.changed | bool }}"

- name: Task Copy helper scripts
  become_user: root
  become: true
  template:
    src: scripts/{{ item }}.j2
    dest: /usr/local/bin/{{ item }}
    force: true
    owner: "root"
    group: "root"
    mode: "0755"
  with_items:
    - peers
    - latest
    - recover-account
    - list-accounts

- name: Task Copy tendermint docker helper script
  become_user: root
  become: true
  template:
    src: scripts/tendermint-container.j2
    dest: /usr/local/bin/{{ tendermint_binary_name }}
    force: true
    owner: "root"
    group: "root"
    mode: "0755"

# - name: copy is validator jailed script
#   become_user: root
#   become: true
#   template:
#     src: scripts/check_val_jailed.j2
#     dest: /usr/local/bin/check_val_jailed.sh
#     force: true
#     owner: "{{ node_user }}"
#     group: "{{ node_user }}"
#     mode: "0755"

# - name: create cron entry for is validator jailed script
#   cron:
#     user: "{{ node_user }}"
#     name: check if validator is jailed
#     minute: "*/15"
#     hour: "*"
#     job: /usr/local/bin/check_val_jailed.sh
#     state: present

# Validator docker ports
- name: Task Set validator docker ports
  set_fact:
    docker_tendermint_ports: "{{ validator_docker_ports }}"

- name: Task Create Zetachain Docker Container
  docker_container:
    name: zetachain
    image: "{{ tendermint_image }}"
    state: started
    memory: "{{ tendermint_docker_memory_limit }}"
    memory_swap: "{{ tendermint_docker_memory_limit }}"
    restart_policy: unless-stopped
    restart: "{{ cfg_changed | bool }}"
    network_mode: host
    ulimits:
      - nofile:65535:65535
    networks_cli_compatible: true
    ports: "{{ validator_docker_ports }}"
    env:
      SERVICE_SCHEME: http
      SERVICE_HOST: "localhost"
    detach: true
    volumes:
      - /root/.zetacored/config:/root/.zetacored/config
      - /data/zetachain:/root/.zetacored/data
      - /root/.zetacored/config/keyring-test:/root/.zetacored/keyring-test
    command: "zetacored start"
